name: Codacy Analysis CLI

on:
  pull_request:
    branches:
      - main

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@33d455949345bddfdb845fba76b57b70cc83754b # v4.4.0
